### ISSUE TITLE
No Reverse?

### ISSUE THREAD

**Issue by Tom-evnut** [aot93/Mini-E-VCU#1]
I noticed there is no VCUstatus == 5 but it does get set:

`Line 1521 VCUstatus = driveReverse; `

Does the current code not work for generating a reverse rotation of the motor? As the Torque control flips around when running in reverse I believe.

**Comment by aot93** [comment]
Not sure I see the problem, the code works correctly.

Reverse is set at line 1521
Then evaluated as a case in the switch at 1672

VCU status definitions start at line 122

**Comment by Tom-evnut** [comment]
My bad, got confused slightly in the code. So no regen available in reverse?

**Comment by aot93** [comment]
Reverse is much simplified, limited torque and speed and no regen.

Perhaps there is a use case where folks have to run the motor in reverse due to mounting orientation.
This could be dealt with better by an option in the settings, which which flips the torque request accordingly I think.
